server:
  adminMinThreads: 1
  adminMaxThreads: 10
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /}
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  applicationConnectors:
    - type: ${APPLICATION_CONNEXTOR_TYPE:- http}
      port: ${APPLICATION_CONNEXTOR_PORT:- 8299}
  adminConnectors:
    - type: ${ADMIN_CONNEXTOR_TYPE:- http}
      port: ${ADMIN_CONNEXTOR_PORT:- 8300}


logging:
  level: ${LOGGING_LEVEL:- ERROR}
  loggers:
    stroom: DEBUG
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
    "AUDIT":
      level: INFO
      appenders:
        - type: console
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

elastic:
  clusterName: ${ELASTIC_CLUSTER_NAME:- docker-cluster}
  hosts: ${ELASTIC_TRANSPORT_HOSTS:- localhost:9300}

token:
  publicKeyUrl: ${JWS_PUBLIC_KEY_URL:- http://stroom-auth-service:8099/token/v1/publickey}
  jwsIssuer: ${JWS_ISSUER:- stroom}
  algorithm: ${JWS_ALGORITHM:- RS256}