language: java
dist: trusty
group: edge
jdk: oraclejdk8
sudo: required # To ensure we get a VM rather than a container for more memory and for all the apt-get stuff

services:
  - docker

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken>`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: MjdvQpO3CVFiT6iT+sGpPfefPJ6QZJhXJRKoe6F3tSBJtiu3FLBf9J44+qOHRmOFMTAKBhYlfk1X34lIG7w2wmUEJWvs9mMN7xIMwuobgciUlTyzQcMaeQwp93hBSIWQ1EC8SmmPOyLDkM7F8rCc8e4phDePV3KGDQz6vnYhhX5IH2pharsmtjH/rBSYrjJ2zPRIUNeDl8+pwZryHH+vj8/3djNfZOKrDxj28DAb5Hd8cM4EEBZ5cGfEaEYXRqITQEfenjQtAFQRI2owFJUkVd1wXD1HcZuLJFCzetARDVok2oujhh/7nNs0HsyLF3ffa5v199OU50V2uH/fcO7EskbYt8k+mDYuq4KXo9JA/rQ711LlGrHndtPQTnyLrJzBOQO1zPKo+tsDyEINjL7UuRZI8z6dD+sk/y7Wj69OqXyb9krar957lUx4eCTIzR96FvgQMTX8ZNsTLPS3gRuPp5HxybalTztW2O2jUF148fOzfm4K+9TofMhrRkSmA21mf+l1mqODilJIRIlUX7o7DAOYnDpnbNWPEK1/GGzpPIH1yajdjMqTatcmjeHpX0MsHBufQFlRuvXBpt2I1tp3PeWCkqk8ddDc4GPaMN5ml4MWmEGT7NiD3nYIeiEzLhaHV1LAg7S+7l+UbQbxLJRI7exzKn3n7bIeyJGOXlvPw5w=

install: echo "skip 'gradle assemble' step to speed up build"

before_script: ./travis.before_script.sh

# Use 1 local worker to avoid using too much memory as each worker will chew up ~500Mb ram
script: ./travis.script.sh

# Push to GitHub releases for any tagged commit - the key was generated by the Travis CLI: `$ travis setup releases`
deploy:
  provider: releases
  api_key:
    secure: ASY22luvUrZQ+HTlx/anZ7yWVzxca9VmZngIhKy3vVA4Lqk2xG3fuKMa0ykLwIXvrr2ucCluY8O2Wjqs2FxTNlj0zS7FvNhNQiPzcufsoaFQM72CDy8kCr7WfYX2IbC/xkxKAyCTHMO+Y86Z2RdwnuZqKVwOIh8wm3QWgrPWRrzl4yzfiDBHwna97Z1Bt6JxBEOhgG4wRyokBZpAnWa7YFw7Nqdi1opPX6VpdYc2k8UPVipDPQ3eyKGrPNSM0sT4WB7HtXQt8fKWHYbIhqB4Zv0pvK/+iwf9K42Eom6n0cTCQiE3yFkkbPPHj5XDSYAchtaEkdQyHLTD+1iHjg/POEvOvCFQwjJEx6+jb1NlGWrRh8nvbudb6lgC4sSdKawjNxAwApLsROiT3J08qdsi/EK/zwNWC5Qt3O6wufx8LWT1Y7b6F4yrT/KsrGuV6wENpsjNGSw/Vmkq7N3aIfOW+8uHGkYEuO5cV7JtJysH03ZG+T0QQp+cgrrgbShDXgYcTT3VHtGEVRMOUvg5qU9HoO4cQ3GCjN071rRdfQs4YOeTFBK3Cbt3b+a1SbVfFNwrqnAfgOmUNIAF/6oeV5HWACGZqkXGxRCU4VdJjQNtZTQGGOBEBLFBHpBN/Pb/N/CjBwkYCLD+ZRYUDWFsXxTcuAxbnXhTLcHcwx22S2cgu0Y=
  file: stroom-query-elastic-svc/build/libs/stroom-query-elastic-all.jar
  skip_cleanup: true
  on:
    repo: gchq/stroom-query-elastic
    tags: true

# Clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - libs
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

