version: '2.1'

services:

  elasticsearch-test:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    container_name: elasticsearch-test
    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
