version: '2.1'

services:

  kibana-test:
    image: "${KIBANA_DOCKER_REPO:-docker.elastic.co/kibana/kibana}:5.6.3"
    container_name: kibana-test
    volumes:
      - ./kibana/:/usr/share/kibana/config
    ports:
      - "5701:5601"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  elasticsearch-test:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    container_name: elasticsearch-test
    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "19200:9200"
      - "19300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
