server:
  adminMinThreads: 1
  adminMaxThreads: 10
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /}
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  applicationConnectors:
    - type: ${APPLICATION_CONNEXTOR_TYPE:- http}
      port: ${APPLICATION_CONNEXTOR_PORT:- 8299}
  adminConnectors:
    - type: ${ADMIN_CONNEXTOR_TYPE:- http}
      port: ${ADMIN_CONNEXTOR_PORT:- 8300}

logging:
  level: ${LOGGING_LEVEL:- ERROR}
  loggers:
    stroom: DEBUG
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
    "AUDIT":
      level: INFO
      appenders:
        - type: fifo
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

elastic:
  clusterName: "docker-cluster"
  hosts:
    "localhost": 9300